/**
 * Images should be stored in the `App/Images` directory and referenced using variables defined here.
 */

export default {
  logo: require('App/Assets/Images/logo.png'),
  // share modal icons
  whatsAppShare: require('App/Assets/Images/modalShare/whatsapp2.png'),
  msgShare: require('App/Assets/Images/modalShare/arrow.png'),
  fbShare: require('App/Assets/Images/modalShare/facebook.png'),
  copyLinkShare: require('App/Assets/Images/modalShare/broken-link.png'),
  smsShare: require('App/Assets/Images/modalShare/comment.png'),
  emailShare: require('App/Assets/Images/modalShare/Google.png'),
  moreChevIcon: require('App/Assets/Images/modalShare/more.png'),
  reportIcon: require('App/Assets/Images/modalShare/report.png'),
  blockIcon: require('App/Assets/Images/modalShare/block.png'),
  sendMsgIcon: require('App/Assets/Images/modalShare/sendMessage.png'),
  // navigator Icons
  homeA: require('App/Assets/Images/navIcons/png/active/home-run.png'),
  homeD: require('App/Assets/Images/navIcons/png/deactive/home-run.png'),
  profileA: require('App/Assets/Images/navIcons/png/active/user.png'),
  profileD: require('App/Assets/Images/navIcons/png/deactive/user.png'),
  messagesA: require('App/Assets/Images/navIcons/png/active/chat.png'),
  messagesD: require('App/Assets/Images/navIcons/png/deactive/chat.png'),
  activityA: require('App/Assets/Images/navIcons/png/active/heart.png'),
  activityD: require('App/Assets/Images/navIcons/png/deactive/heart.png'),
  // other icons and btn icons
  bookmarkIcon: require('App/Assets/Images/bookmark.png'),
  voiceIcon: require('App/Assets/Images/microphone.png'),
  sendIcon: require('App/Assets/Images/send.png'),
  attachIcon: require('App/Assets/Images/attach.png'),
  addIcon: require('App/Assets/Images/add.png'),
  fbRound: require('App/Assets/Images/fbLink.png'),
  contactsRound: require('App/Assets/Images/Contacts.png'),
  addRound: require('App/Assets/Images/addRound.png'),
  menuIcon: require('App/Assets/Images/profileTabIcon/active/four-squares.png'),
  menuIconD: require('App/Assets/Images/profileTabIcon/deactive/four-squares.png'),
  backIcon: require('App/Assets/Images/backChevron.png'),
  nextIcon: require('App/Assets/Images/next.png'),
  plusIcon: require('App/Assets/Images/plus.png'),
  copyIcon: require('App/Assets/Images/copy.png'),
  likeIconA: require('App/Assets/Images/profileTabIcon/active/heart.png'),
  likeIconD: require('App/Assets/Images/profileTabIcon/deactive/heart.png'),
  heartIcon: require('App/Assets/Images/heartFav.png'),
  uploadIcon: require('App/Assets/Images/uploadMask.png'),
  newPostIcon: require('App/Assets/Images/newPost.png'),
  moreIcon: require('App/Assets/Images/more.png'),
  borkenLinkIcon: require('App/Assets/Images/broken-link.png'),
  searchIcon: require('App/Assets/Images/search.png'),
  rect: require('App/Assets/Images/Rectangle.png'),
  notifIcon: require('App/Assets/Images/notification.png'),
  langIcon: require('App/Assets/Images/global.png'),
  themeIcon: require('App/Assets/Images/paint.png'),
  questionIcon: require('App/Assets/Images/question.png'),
  sheetIcon: require('App/Assets/Images/sheet.png'),
  shieldIcon: require('App/Assets/Images/shield.png'),
  rulesIcon: require('App/Assets/Images/accept.png'),
  accountIcon: require('App/Assets/Images/account.png'),
  noChat: require('App/Assets/Images/noChat.png'),
  Ellipse: require('App/Assets/Images/Ellipse.png'),
  Instagram: require('App/Assets/Images/instagram.png'),
  downArrow: require('App/Assets/Images/downArrow.png'),
  // oauths icon
  phoneEmailAuth: require('../Assets/Images/oauths/phoneEmailauth.png'),
  fbAuth: require('../Assets/Images/oauths/fbAuth.png'),
  twitterAuth: require('../Assets/Images/oauths/twitterAuth.png'),
  googleAuth: require('../Assets/Images/oauths/googleAuth.png'),
  appleAuth: require('../Assets/Images/oauths/appleAuth.png'),
  // dynamic signups
  profileSignup: require('../Assets/Images/userSignup.png'),
  activitySignup: require('../Assets/Images/activitySignup.png'),

  // mock will be removed
  profilePic: require('App/Assets/Images/mock/profilePic.png'),
  manProfile: require('App/Assets/Images/mock/manProfile.png'),
  carProfile: require('App/Assets/Images/mock/carProfile.png'),
  post1: require('App/Assets/Images/mock/1.png'),
  post2: require('App/Assets/Images/mock/2.png'),
  post3: require('App/Assets/Images/mock/3.png'),
  post4: require('App/Assets/Images/mock/4.png'),
  post5: require('App/Assets/Images/mock/5.png'),
  post6: require('App/Assets/Images/mock/6.png'),
  msg1: require('App/Assets/Images/mock/msg1.png'),
  msg2: require('App/Assets/Images/mock/msg2.png'),
  msg3: require('App/Assets/Images/mock/msg3.png'),
  msg4: require('App/Assets/Images/mock/msg4.png'),
  msg5: require('App/Assets/Images/mock/msg5.png'),
  msg6: require('App/Assets/Images/mock/msg6.png'),
  msg7: require('App/Assets/Images/mock/msg7.png'),
  flw1: require('App/Assets/Images/mock/flw1.png'),
  flw2: require('App/Assets/Images/mock/flw2.png'),
  flw3: require('App/Assets/Images/mock/flw3.png'),
  flw4: require('App/Assets/Images/mock/flw4.png'),
  flw5: require('App/Assets/Images/mock/flw5.png'),
}
